quarkus:
  log:
    level: ERROR
    format: "%d{yyyy-MM-dd HH:mm:ss,SSS} %-5p [%c{1.1.1.1.1.3}] %s%e%n"
    category:
      "me.l3n.bot.discord":
        level: DEBUG
    file:
      enable: true
      path: logs/quarkus.log
      format: ${quarkus.log.format}
      rotation:
        max-file-size: 10M
        max-backup-index: 5
        rotate-on-boot: true
    console:
      format: ${quarkus.log.format}

cron-expr: "* 0 9,12,15,18,21 * * ? *"
"%dev":
  cron-expr: "*/5 * * * * ?"

url:
  goodreads-quotes: https://www.goodreads.com/quotes
  pensador:
    base: https://www.pensador.com
    populares: ${url.pensador.base}/populares

source: pensador
