quarkus:
  log:
    level: ERROR
    category:
      "me.l3n.bot.discord":
        level: DEBUG

cron-expr: "* 0 9,13,17 * * ? *"
"%dev":
  cron-expr: "*/15 * * * * ?"

quotes-url:
  goodreads: https://www.goodreads.com/quotes
  pensador: https://www.pensador.com/populares
