name: Quarkus build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Validate tests
      uses: gradle/gradle-build-action@4137be6a8bf7d7133955359dbd952c0ca73b1021
      with:
        arguments: "test"
    - name: Build Quarkus
      uses: gradle/gradle-build-action@4137be6a8bf7d7133955359dbd952c0ca73b1021
      with:
        arguments: "quarkusBuild"
    - name: Archive build
      uses: thedoctor0/zip-release@master
      with:
        filename: quarkusPackage
        directory: build/quarkus-app
    - name: Upload archive
      uses: ncipollo/release-action@v1
      with:
        artifacts: "quarkusPackage.zip"
        token: ${{ secrets.GITHUB_TOKEN }}
