name: Release Quarkus package

on:
  push:
    branches: [ main ]
  # TODO: remove, it's just to test
  pull_request:
  
jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
        
    - name: Validate tests
      uses: gradle/gradle-build-action@4137be6a8bf7d7133955359dbd952c0ca73b1021
      with:
        arguments: "test"
        
    - name: Build Java Quarkus
      run: "./gradlew quarkusBuild"
    - name: Archive Java build
      uses: thedoctor0/zip-release@master
      with:
        filename: quarkusPackage.zip
        directory: build/quarkus-app

    - name: Build Native Quarkus
      uses: uraimo/run-on-arch-action@v2
      with:
        arch: armv7
        distro: ubuntu18.04
        githubToken: ${{ secrets.GITHUB_TOKEN }}
        run: |
          wget https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-21.3.0/graalvm-ce-java11-linux-aarch64-21.3.0.tar.gz
          tar -xzf graalvm-ce-java11-linux-aarch64-21.3.0.tar.gz
          export GRAALVM_FOLDER=$(pwd)/graalvm-ce-java11-21.3.0
          export PATH=$GRAALVM_FOLDER/bin:$PATH
          export JAVA_HOME=$GRAALVM_FOLDER
          java -version
          ./gradlew build -Dquarkus.package.type=native
        
    - name: Upload archive
      uses: ncipollo/release-action@v1.8.10
      with:
        artifacts: "build/quarkus-app/quarkusPackage.zip"
        token: ${{ secrets.GITHUB_TOKEN }}
        allowUpdates: true
        removeArtifacts: true
        artifactErrorsFailBuild: true
        prerelease: true
        name: latest
        tag: latest
