name: Release Quarkus package

on:
  push:
    branches: [ main ]
  # TODO: remove, it's just to test
  pull_request:
  
jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Validate tests
      uses: gradle/gradle-build-action@4137be6a8bf7d7133955359dbd952c0ca73b1021
      with:
        arguments: "test"
    - name: Build Jar Quarkus
      run: "./gradlew quarkusBuild"
    - name: Setup ARM64 GraalVM
      uses: DeLaGuardo/setup-graalvm@5.0
      with:
        graalvm: '21.0.0.2'
        java: 'java11'
        arch: 'aarch64'
    - name: Build Native Quarkus
      uses: uraimo/run-on-arch-action@v2.1.0
      with:
        arch: armv7
        distro: ubuntu18.04
        run: "./gradlew build -Dquarkus.package.type=native"
    - name: Archive Jar build
      uses: thedoctor0/zip-release@master
      with:
        filename: quarkusPackage.zip
        directory: build/quarkus-app
    - name: Upload archive
      uses: ncipollo/release-action@v1.8.10
      with:
        artifacts: "build/quarkus-app/quarkusPackage.zip"
        token: ${{ secrets.GITHUB_TOKEN }}
        allowUpdates: true
        removeArtifacts: true
        artifactErrorsFailBuild: true
        prerelease: true
        name: latest
        tag: latest
